openapi: 3.0.0
info:
  title: User Balance API
  version: 1.0.0
servers:
  - url: https://api.example.com

paths:
  /api/user/balance:
    get:
      summary: Retrieve user loyalty points balance
      tags:
        - Balance
      security:
        - bearerAuth: []
        - cookieAuth: []
      responses:
        '200':
          description: Successful retrieval of balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '401':
          description: User is not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    BalanceResponse:
      type: object
      properties:
        current:
          type: number
          format: float
          description: Current loyalty points balance
          example: 500.5
        withdrawn:
          type: number
          format: float
          description: Total points withdrawn during account lifetime
          example: 42
      required:
        - current
        - withdrawn
    Error:
      type: object
      properties:
        message:
          type: string
          example: "Error description"
      required:
        - message

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token
