version: '3.0'

includes:
  mockery:
    taskfile: taskfiles/Mockery.yaml
    internal: true

  sqlc:
    taskfile: taskfiles/Sqlc.yaml
    internal: true

vars:
  ROOT:
    sh: pwd

  MICROSERVICES:
    sh: ls microservices/

tasks:
  generate:sqlc:
    cmds:
      - for: { var: MICROSERVICES, as: MICROSERVICE }
        vars:
          ROOT: "{{ .ROOT }}"
          DIR: "microservices/{{ .MICROSERVICE }}"
        task: sqlc:run:codegen

  generate:mockery:
    cmds:
      - for: { var: MICROSERVICES, as: MICROSERVICE }
        vars:
          ROOT: "{{ .ROOT }}"
          DIR: "microservices/{{ .MICROSERVICE }}"
        task: mockery:run:codegen
