openapi: 3.0.0
info:
  title: User Authntication API
  version: 1.0.0
  description: Authenticate user
  contact:
    name: Minimarket OJSC
    email: minimarket@admin.com
    url: https://github.com/PiskarevSA/minimarket
servers:
  - url: https://api.example.com
tags:
  - name: Points
paths:
  /api/user/points:
    post:
      operationId: pointsBalance
      description: Retrieve user loyalty points balance
      tags:
        - Points
      security:
        - bearerAuth: []
        - cookieAuth: []
      responses:
        '200':
          description: Successful retrieval of balance
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Balance'
        '401':
          description: User is not authenticated
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/UserUnauthenticated'
        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/InternalError'
  /api/user/points/withdraw:
    post:
      operationId: pointsWithdraw
      description: Withdraw loyalty points for a new order
      tags:
        - Points
      security:
        - bearerAuth: []
        - cookieAuth: []
      requestBody:
        description: Order number and amount of points to withdraw
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Withdraw'
      responses:
        '200':
          description: Withdrawal request processed successfully
        '402':
          description: Insufficient points on account
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/InsufficientPoints'
        '422':
          description: Invalid order number format
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/InvalidOrderNumber'
        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/InternalError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token
  schemas:
    Balance:
      type: object
      properties:
        current:
          type: number
          format: float
          description: Current loyalty points balance
          example: 500.5
        withdrawn:
          type: number
          format: float
          description: Total points withdrawn during account lifetime
          example: 42
      required:
        - current
        - withdrawn
    UserUnauthenticated:
      type: object
      properties:
        code:
          type: string
          enum:
            - U1527
        message:
          type: string
          enum:
            - user is not authenticated
      required:
        - code
        - message
    InternalError:
      type: object
      properties:
        code:
          type: string
          enum:
            - S1394
        message:
          type: string
          enum:
            - internal error
      required:
        - code
        - message
    Withdraw:
      type: object
      properties:
        order:
          type: string
          description: Order number for which points are withdrawn
          example: '2377225624'
          x-oapi-codegen-extra-tags:
            validate: required
        sum:
          type: number
          description: Amount of points to withdraw
          minimum: 1
          example: 751
          x-oapi-codegen-extra-tags:
            validate: required, min=1
      required:
        - order
        - sum
    InsufficientPoints:
      type: object
      properties:
        code:
          type: string
          enum:
            - U1688
        message:
          type: string
          enum:
            - insufficient points on account
      required:
        - code
        - message
    InvalidOrderNumber:
      type: object
      properties:
        code:
          type: string
          enum:
            - U1062
        message:
          type: string
          enum:
            - invalid order number
      required:
        - code
        - message
