openapi: 3.0.0
info:
  title: User Authntication API
  version: 1.0.0
  description: Authenticate user
  contact:
    name: Minimarket OJSC
    email: minimarket@admin.com
    url: https://github.com/PiskarevSA/minimarket
servers:
  - url: https://api.example.com

tags:
  - name: Points

paths:
  /api/user/points:
    $ref: "paths/balance.yaml"

  /api/user/points/withdraw:
    $ref: "paths/withdraw.yaml"

components:
  securitySchemes:
    $ref: "components/schemas/Security.yaml"