openapi: 3.0.0
info:
  title: User Authntication API
  version: 1.0.0
  description: Authenticate user
  contact:
    name: Minimarket OJSC
    email: minimarket@admin.com
    url: https://github.com/PiskarevSA/minimarket
servers:
  - url: https://api.example.com
tags:
  - name: User
paths:
  /api/user/register:
    post:
      operationId: userRegister
      description: Register a new user and authenticate
      tags:
        - User
      requestBody:
        description: User credentials for registration
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: User successfully registered and authenticated
          headers:
            Set-Cookie:
              description: Authentication cookie
              schema:
                type: string
            Authorization:
              description: Bearer token for authenticated sessions
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authenticated'
        '400':
          description: Invalid payload format
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/InvalidPayloadFormat'
        '409':
          description: Login already in use
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/LoginConflict'
        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/InternalError'
  /api/user/login:
    post:
      operationId: userLogin
      description: Authenticate a user
      tags:
        - User
      requestBody:
        description: User credentials for registration
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: User successfully authenticated
          headers:
            Set-Cookie:
              description: Authentication cookie
              schema:
                type: string
            Authorization:
              description: Bearer token for authenticated sessions
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authenticated'
        '400':
          description: Invalid payload format
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/InvalidPayloadFormat'
        '401':
          description: Invalid login or password
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/InvalidLoginOrPassword'
        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/InternalError'
components:
  schemas:
    Login:
      type: object
      properties:
        login:
          type: string
          minLength: 5
          maxLength: 32
          example: johndoe
          x-oapi-codegen-extra-tags:
            validate: required, min=5,max=32
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 32
          example: S3cur3P@ssw0rd
          x-oapi-codegen-extra-tags:
            validate: required, min=8,max=32
      required:
        - login
        - password
    Authenticated:
      type: object
      properties:
        id:
          type: string
          example: 292a6b41-550f-43d5-ba34-450b0f06f3a7
          x-oapi-codegen-extra-tags:
            validate: required
        login:
          type: string
          minLength: 5
          maxLength: 32
          example: johndoe
          x-oapi-codegen-extra-tags:
            validate: required, min=5,max=32
      required:
        - id
        - login
    InvalidPayloadFormat:
      type: object
      properties:
        code:
          type: string
          enum:
            - U1402
        message:
          type: string
          enum:
            - invalid payload format
      required:
        - code
        - message
    LoginConflict:
      type: object
      properties:
        code:
          type: string
          enum:
            - U1956
        message:
          type: string
          enum:
            - login already in use
      required:
        - code
        - message
    InternalError:
      type: object
      properties:
        code:
          type: string
          enum:
            - S1394
        message:
          type: string
          enum:
            - internal error
      required:
        - code
        - message
    InvalidLoginOrPassword:
      type: object
      properties:
        code:
          type: string
          enum:
            - U1385
        message:
          type: string
          enum:
            - invalid login or password
      required:
        - code
        - message
