openapi: 3.0.0
info:
  title: User Authntication API
  version: 1.0.0
  description: Authenticate user
  contact:
    name: Minimarket OJSC
    email: minimarket@admin.com
    url: https://github.com/PiskarevSA/minimarket
servers:
  - url: https://api.example.com

tags:
  - name: User

paths:
  /api/user/register:
    $ref: "paths/register.yaml"
  /api/user/login:
    $ref: "paths/login.yaml"