// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"context"
	json "github.com/bytedance/sonic"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for InsufficientPointsCode.
const (
	U1688 InsufficientPointsCode = "U1688"
)

// Defines values for InsufficientPointsMessage.
const (
	InsufficientPointsOnAccount InsufficientPointsMessage = "insufficient points on account"
)

// Defines values for InternalErrorCode.
const (
	S1394 InternalErrorCode = "S1394"
)

// Defines values for InternalErrorMessage.
const (
	InternalErrorMessageInternalError InternalErrorMessage = "internal error"
)

// Defines values for InvalidOrderNumberCode.
const (
	U1062 InvalidOrderNumberCode = "U1062"
)

// Defines values for InvalidOrderNumberMessage.
const (
	InvalidOrderNumberMessageInvalidOrderNumber InvalidOrderNumberMessage = "invalid order number"
)

// Defines values for UserUnauthenticatedCode.
const (
	U1527 UserUnauthenticatedCode = "U1527"
)

// Defines values for UserUnauthenticatedMessage.
const (
	UserIsNotAuthenticated UserUnauthenticatedMessage = "user is not authenticated"
)

// Balance defines model for Balance.
type Balance struct {
	// Current Current loyalty points balance
	Current float32 `json:"current"`

	// Withdrawn Total points withdrawn during account lifetime
	Withdrawn float32 `json:"withdrawn"`
}

// InsufficientPoints defines model for InsufficientPoints.
type InsufficientPoints struct {
	Code    InsufficientPointsCode    `json:"code"`
	Message InsufficientPointsMessage `json:"message"`
}

// InsufficientPointsCode defines model for InsufficientPoints.Code.
type InsufficientPointsCode string

// InsufficientPointsMessage defines model for InsufficientPoints.Message.
type InsufficientPointsMessage string

// InternalError defines model for InternalError.
type InternalError struct {
	Code    InternalErrorCode    `json:"code"`
	Message InternalErrorMessage `json:"message"`
}

// InternalErrorCode defines model for InternalError.Code.
type InternalErrorCode string

// InternalErrorMessage defines model for InternalError.Message.
type InternalErrorMessage string

// InvalidOrderNumber defines model for InvalidOrderNumber.
type InvalidOrderNumber struct {
	Code    InvalidOrderNumberCode    `json:"code"`
	Message InvalidOrderNumberMessage `json:"message"`
}

// InvalidOrderNumberCode defines model for InvalidOrderNumber.Code.
type InvalidOrderNumberCode string

// InvalidOrderNumberMessage defines model for InvalidOrderNumber.Message.
type InvalidOrderNumberMessage string

// UserUnauthenticated defines model for UserUnauthenticated.
type UserUnauthenticated struct {
	Code    UserUnauthenticatedCode    `json:"code"`
	Message UserUnauthenticatedMessage `json:"message"`
}

// UserUnauthenticatedCode defines model for UserUnauthenticated.Code.
type UserUnauthenticatedCode string

// UserUnauthenticatedMessage defines model for UserUnauthenticated.Message.
type UserUnauthenticatedMessage string

// Withdraw defines model for Withdraw.
type Withdraw struct {
	// Order Order number for which points are withdrawn
	Order string `json:"order" validate:"required"`

	// Sum Amount of points to withdraw
	Sum float32 `json:"sum" validate:"required, min=1"`
}

// PointsWithdrawJSONRequestBody defines body for PointsWithdraw for application/json ContentType.
type PointsWithdrawJSONRequestBody = Withdraw

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/user/points)
	PointsBalance(w http.ResponseWriter, r *http.Request)

	// (POST /api/user/points/withdraw)
	PointsWithdraw(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /api/user/points)
func (_ Unimplemented) PointsBalance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/user/points/withdraw)
func (_ Unimplemented) PointsWithdraw(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PointsBalance operation middleware
func (siw *ServerInterfaceWrapper) PointsBalance(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PointsBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PointsWithdraw operation middleware
func (siw *ServerInterfaceWrapper) PointsWithdraw(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PointsWithdraw(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/points", wrapper.PointsBalance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/points/withdraw", wrapper.PointsWithdraw)
	})

	return r
}

type PointsBalanceRequestObject struct {
}

type PointsBalanceResponseObject interface {
	VisitPointsBalanceResponse(w http.ResponseWriter) error
}

type PointsBalance200ApplicationProblemPlusJSONResponse Balance

func (response PointsBalance200ApplicationProblemPlusJSONResponse) VisitPointsBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(200)

	return json.ConfigDefault.NewEncoder(w).Encode(response)
}

type PointsBalance401ApplicationProblemPlusJSONResponse UserUnauthenticated

func (response PointsBalance401ApplicationProblemPlusJSONResponse) VisitPointsBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.ConfigDefault.NewEncoder(w).Encode(response)
}

type PointsBalance500ApplicationProblemPlusJSONResponse InternalError

func (response PointsBalance500ApplicationProblemPlusJSONResponse) VisitPointsBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.ConfigDefault.NewEncoder(w).Encode(response)
}

type PointsWithdrawRequestObject struct {
	Body *PointsWithdrawJSONRequestBody
}

type PointsWithdrawResponseObject interface {
	VisitPointsWithdrawResponse(w http.ResponseWriter) error
}

type PointsWithdraw200Response struct {
}

func (response PointsWithdraw200Response) VisitPointsWithdrawResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PointsWithdraw402ApplicationProblemPlusJSONResponse InsufficientPoints

func (response PointsWithdraw402ApplicationProblemPlusJSONResponse) VisitPointsWithdrawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(402)

	return json.ConfigDefault.NewEncoder(w).Encode(response)
}

type PointsWithdraw422ApplicationProblemPlusJSONResponse InvalidOrderNumber

func (response PointsWithdraw422ApplicationProblemPlusJSONResponse) VisitPointsWithdrawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.ConfigDefault.NewEncoder(w).Encode(response)
}

type PointsWithdraw500ApplicationProblemPlusJSONResponse InternalError

func (response PointsWithdraw500ApplicationProblemPlusJSONResponse) VisitPointsWithdrawResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.ConfigDefault.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/user/points)
	PointsBalance(ctx context.Context, request PointsBalanceRequestObject) (PointsBalanceResponseObject, error)

	// (POST /api/user/points/withdraw)
	PointsWithdraw(ctx context.Context, request PointsWithdrawRequestObject) (PointsWithdrawResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PointsBalance operation middleware
func (sh *strictHandler) PointsBalance(w http.ResponseWriter, r *http.Request) {
	var request PointsBalanceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PointsBalance(ctx, request.(PointsBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PointsBalance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PointsBalanceResponseObject); ok {
		if err := validResponse.VisitPointsBalanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PointsWithdraw operation middleware
func (sh *strictHandler) PointsWithdraw(w http.ResponseWriter, r *http.Request) {
	var request PointsWithdrawRequestObject

	var body PointsWithdrawJSONRequestBody
	if err := json.ConfigDefault.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PointsWithdraw(ctx, request.(PointsWithdrawRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PointsWithdraw")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PointsWithdrawResponseObject); ok {
		if err := validResponse.VisitPointsWithdrawResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
