package: oapi

generate:
  chi-server: true
  strict-server: true
  models: true
  embedded-spec: false

output: internal/handlers/oapi/oapi.gen.go
output-options:
  name-normalizer: ToCamelCaseWithInitialisms
