// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	json "github.com/bytedance/sonic"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for InternalServerErrorCode.
const (
	S1394 InternalServerErrorCode = "S1394"
)

// Defines values for InternalServerErrorMessage.
const (
	InternalServerError InternalServerErrorMessage = "internal server error"
)

// Defines values for InvalidLoginOrPasswordCode.
const (
	U1385 InvalidLoginOrPasswordCode = "U1385"
)

// Defines values for InvalidLoginOrPasswordMessage.
const (
	InvalidLoginOrPassword InvalidLoginOrPasswordMessage = "invalid login or password"
)

// Defines values for InvalidPayloadFormatCode.
const (
	U1402 InvalidPayloadFormatCode = "U1402"
)

// Defines values for InvalidPayloadFormatMessage.
const (
	InvalidPayloadFormat InvalidPayloadFormatMessage = "invalid payload format"
)

// Defines values for LoginConflictCode.
const (
	U1956 LoginConflictCode = "U1956"
)

// Defines values for LoginConflictMessage.
const (
	LoginAlreadyInUse LoginConflictMessage = "login already in use"
)

// Authenticated defines model for Authenticated.
type Authenticated struct {
	ID    string `json:"id" validate:"required"`
	Login string `json:"login" validate:"required, min=5,max=32"`
}

// InternalServerErrorResponse defines model for InternalServerError.
type InternalServerErrorResponse struct {
	Code    InternalServerErrorCode    `json:"code"`
	Message InternalServerErrorMessage `json:"message"`
}

// InternalServerErrorCode defines model for InternalServerError.Code.
type InternalServerErrorCode string

// InternalServerErrorMessage defines model for InternalServerError.Message.
type InternalServerErrorMessage string

// InvalidLoginOrPasswordResponse defines model for InvalidLoginOrPassword.
type InvalidLoginOrPasswordResponse struct {
	Code    InvalidLoginOrPasswordCode    `json:"code"`
	Message InvalidLoginOrPasswordMessage `json:"message"`
}

// InvalidLoginOrPasswordCode defines model for InvalidLoginOrPassword.Code.
type InvalidLoginOrPasswordCode string

// InvalidLoginOrPasswordMessage defines model for InvalidLoginOrPassword.Message.
type InvalidLoginOrPasswordMessage string

// InvalidPayloadFormatResponse defines model for InvalidPayloadFormat.
type InvalidPayloadFormatResponse struct {
	Code    InvalidPayloadFormatCode    `json:"code"`
	Message InvalidPayloadFormatMessage `json:"message"`
}

// InvalidPayloadFormatCode defines model for InvalidPayloadFormat.Code.
type InvalidPayloadFormatCode string

// InvalidPayloadFormatMessage defines model for InvalidPayloadFormat.Message.
type InvalidPayloadFormatMessage string

// Login defines model for Login.
type Login struct {
	Login    string `json:"login" validate:"required, min=5,max=32"`
	Password string `json:"password" validate:"required, min=8,max=32"`
}

// LoginConflictResponse defines model for LoginConflict.
type LoginConflictResponse struct {
	Code    LoginConflictCode    `json:"code"`
	Message LoginConflictMessage `json:"message"`
}

// LoginConflictCode defines model for LoginConflict.Code.
type LoginConflictCode string

// LoginConflictMessage defines model for LoginConflict.Message.
type LoginConflictMessage string

// UserLoginJSONRequestBody defines body for UserLogin for application/json ContentType.
type UserLoginJSONRequestBody = Login

// UserRegisterJSONRequestBody defines body for UserRegister for application/json ContentType.
type UserRegisterJSONRequestBody = Login

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/user/login)
	UserLogin(w http.ResponseWriter, r *http.Request)

	// (POST /api/user/register)
	UserRegister(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /api/user/login)
func (_ Unimplemented) UserLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/user/register)
func (_ Unimplemented) UserRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UserLogin operation middleware
func (siw *ServerInterfaceWrapper) UserLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserRegister operation middleware
func (siw *ServerInterfaceWrapper) UserRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/login", wrapper.UserLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/register", wrapper.UserRegister)
	})

	return r
}

type UserLoginRequestObject struct {
	Body *UserLoginJSONRequestBody
}

type UserLoginResponseObject interface {
	VisitUserLoginResponse(w http.ResponseWriter) error
}

type UserLogin200ResponseHeaders struct {
	Authorization string
	SetCookie     string
}

type UserLogin200JSONResponse struct {
	Body    Authenticated
	Headers UserLogin200ResponseHeaders
}

func (response UserLogin200JSONResponse) VisitUserLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Authorization", fmt.Sprint(response.Headers.Authorization))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.ConfigDefault.NewEncoder(w).Encode(response.Body)
}

type UserLogin400JSONResponse InvalidPayloadFormatResponse

func (response UserLogin400JSONResponse) VisitUserLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.ConfigDefault.NewEncoder(w).Encode(response)
}

type UserLogin401JSONResponse InvalidLoginOrPasswordResponse

func (response UserLogin401JSONResponse) VisitUserLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.ConfigDefault.NewEncoder(w).Encode(response)
}

type UserLogin500JSONResponse InternalServerErrorResponse

func (response UserLogin500JSONResponse) VisitUserLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.ConfigDefault.NewEncoder(w).Encode(response)
}

type UserRegisterRequestObject struct {
	Body *UserRegisterJSONRequestBody
}

type UserRegisterResponseObject interface {
	VisitUserRegisterResponse(w http.ResponseWriter) error
}

type UserRegister200ResponseHeaders struct {
	Authorization string
	SetCookie     string
}

type UserRegister200JSONResponse struct {
	Body    Authenticated
	Headers UserRegister200ResponseHeaders
}

func (response UserRegister200JSONResponse) VisitUserRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Authorization", fmt.Sprint(response.Headers.Authorization))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.ConfigDefault.NewEncoder(w).Encode(response.Body)
}

type UserRegister400JSONResponse InvalidPayloadFormatResponse

func (response UserRegister400JSONResponse) VisitUserRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.ConfigDefault.NewEncoder(w).Encode(response)
}

type UserRegister409JSONResponse LoginConflictResponse

func (response UserRegister409JSONResponse) VisitUserRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.ConfigDefault.NewEncoder(w).Encode(response)
}

type UserRegister500JSONResponse InternalServerErrorResponse

func (response UserRegister500JSONResponse) VisitUserRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.ConfigDefault.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/user/login)
	UserLogin(ctx context.Context, request UserLoginRequestObject) (UserLoginResponseObject, error)

	// (POST /api/user/register)
	UserRegister(ctx context.Context, request UserRegisterRequestObject) (UserRegisterResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// UserLogin operation middleware
func (sh *strictHandler) UserLogin(w http.ResponseWriter, r *http.Request) {
	var request UserLoginRequestObject

	var body UserLoginJSONRequestBody
	if err := json.ConfigDefault.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UserLogin(ctx, request.(UserLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UserLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UserLoginResponseObject); ok {
		if err := validResponse.VisitUserLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UserRegister operation middleware
func (sh *strictHandler) UserRegister(w http.ResponseWriter, r *http.Request) {
	var request UserRegisterRequestObject

	var body UserRegisterJSONRequestBody
	if err := json.ConfigDefault.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UserRegister(ctx, request.(UserRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UserRegister")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UserRegisterResponseObject); ok {
		if err := validResponse.VisitUserRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWTW/bOBP+K8S871GKZMtOEwEFmga7QBZe1KjRU5HDWBrLTCSSS1KJvYH++4KUv1Qr",
	"3hTrAj30ZlPDmed55oPzApmslBQkrIH0BUy2pAr9z5vaLklYnqGl3B0oLRVpy8l/5v6MVlipkiCF4fUQ",
	"L+ejQTgex4twlOTjcI7JKByN43m8iC8XCb6DAOxaOWtjNRcFBLAKJSoeZjKngkRIK6sxtFj4GE9Y8hyt",
	"u6Dpr5pryqFpAihlwUU3/INcilwSBFDhakKisEtIk2EAFRfbv+P/Hj5gFRfvx0GFq/fJEBqHZgct/epU",
	"2cK730WT8wfKLDQB3AlLWmA5I/1E+jetpT5W1oHx5ERdOZ+zQXI9OnC3Ad8EUJExWHSM+SYCMz4EIx/j",
	"+PI3uH3MvcMj7E6pQoYCK3fYQ+MzGSWFoZalV27iZPikp2jMs9T5vxP9Mkiuxm8n6oMwLzaTmqltnLOT",
	"7WPTw3eK61Ji/rvUFdq3sB3Fw+9lq9oYbNEG+TFUO0QOiU62fddl9hO1YwDqoNz2eGZJVutk+sGY51i7",
	"Ht0ImO7tT0G9OhfUq1cnRyviAf6++eETcCvFouTZm0rsenz51hJrGwlLTZivGResNnTuAuvg31eWc8rF",
	"QrYchMWWHFXIS0hdIniF+pHsB8wrLi4yWUEAG59/7r6yT3/MbiGAWrtbS2uVSaOo4HZZz92daMrNI2p6",
	"mt1Ee59OjpxMprmyXApIOy+fU0G7d4tbX0hfDGnmDNrvXAp2M72DAJ5Im/b64CK+iJ1XqUig4pBC4o9c",
	"cu3SZypCxSPnOto1j5LGsz6BBbdoXNJ98Lt8g2myKR+XGzL2o8zXWzVJeL+oVLmBHD0YKfbPvfv1f00L",
	"SOF/0X4fiDbLQNT69lnqgvNiZJpyhxBL48YS01RwY1t4cFgsVtfkq6dNu9dhGMdng9ldWF6Da+osI2MW",
	"dVmuGXauBLAkzEnv1h+p+d8tj6O8fCTUpJmVjyQ87Y4rZsi4ajAQHIA/7qQZ2fBWykdOJzPvqixrzU75",
	"cx5HZxS0913r0fWu/3HyaAbnRvPtVnECz/Fq0AQwPqtAx+tcL56+nczZte/FV1+ZcO9O9oOh7SPSr8+G",
	"zxsLhkzQs58NDEXeKcXeYbG9+GtefOe82OaE8iOhf42PHzE+rs9blLvVqQfGpG//+dkHRhNAa+NOX44Y",
	"ZXsfrsgsGctFwVStlXQddbgrpVE0GL5zi8rFIL0aXQ6gud8FfNluWz5wc9/8EwAA//9KpqShORAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
