name: go vet test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:

  statictest:
    runs-on: ubuntu-latest
    container: golang:1.24
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - if: ${{ env.ACT }}
        name: Hack container for local development
        run: |
            curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
            apt-get install -y nodejs

      - name: Download statictest binary
        uses: robinraju/release-downloader@v1.8
        with:
          repository: Yandex-Practicum/go-autotests
          latest: true
          fileName: statictest
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
          mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Run statictest
        run: |
          go vet -vettool=$(which statictest) ./...
